export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  about: '/about',
  lounge: '/lounge',
  loungeEvent: '/lounge/events/:eventSlug',
  loungeMaze: '/lounge/maze',
  loungeMazeSet: '/lounge/maze/:setSlug',
  loungeMazePlay: '/lounge/maze/:setSlug/play',
  calendar: '/calendar',
  report: '/report',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminUserActivity: '/admin/users/:userId/activity',
  adminLounge: '/admin/lounge',
  adminLoungeContent: '/admin/lounge/:nodeId',
  adminKakaoShare: '/admin/kakao-share',
  adminInquiries: '/admin/inquiries',
  adminInquiryDetail: '/admin/inquiries/:inquiryId',
  profile: '/profile',
  inputPreview: '/preview/input-field',
  dropdownPreview: '/preview/dropdown',
  popupPreview: '/preview/popup',
  searchPreview: '/preview/search-box',
} as const;
