export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  about: '/about',
  calendar: '/calendar',
  report: '/report',
  admin: '/admin',
  adminInquiries: '/admin/inquiries',
  adminInquiryDetail: '/admin/inquiries/:inquiryId',
  profile: '/profile',
  inputPreview: '/preview/input-field',
  dropdownPreview: '/preview/dropdown',
  popupPreview: '/preview/popup',
  searchPreview: '/preview/search-box',
} as const;
